permalink: /
pygments: true
prose:
  rooturl: "_posts"
  markdown: kramdown
  metadata:
    "_posts":
      layout: "post2"
      title: "Title of your article"
      permalink: "e/FIXME"
      mozilla: true
      comments: false
